In [2]:
import numpy as np
a = np.arange(6)                   
print(a)
b = np.arange(12).reshape(4, 3)   
print(b)
c = np.arange(24).reshape(2, 3, 4) 
print(c)


[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)
c = a - b
print(c)
print(b**2)
print(10 * np.sin(a))
a < 35

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


array([ True,  True, False, False])

In [12]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)  
print(A @ B)   
A.dot(B)  

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


array([[5, 4],
       [3, 4]])

In [13]:
import numpy as np

rg = np.random.default_rng()
a = rg.random((2, 3))

print(a)
print(a.sum())
print(a.min())
print(a.max())


[[0.30377601 0.39929908 0.04402162]
 [0.4884323  0.34482259 0.10770018]]
1.6880517887993638
0.04402162234535556
0.4884322987576937


In [17]:
b = np.arange(12).reshape(3, 4)
print(b)
print(b.sum(axis=0))    
print(b.min(axis=1))    
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [20]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))
C = np.array([2., -1., 4.])
print(np.add(B, C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


In [19]:
for row in b:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [22]:
a = np.floor(10 * rg.random((3, 4)))
print(a)
print(a.shape)

[[0. 7. 9. 6.]
 [3. 6. 8. 4.]
 [3. 7. 7. 1.]]
(3, 4)


In [5]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a          
b is a           

True

In [8]:
d = a.copy()  
print(d is a)
print(d.base is a )
d[0, 0] = 9999
a

False
False


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
import numpy as np

rg = np.random.default_rng() 

a = np.floor(10 * rg.random((2, 2)))
print(a)

b = np.floor(10 * rg.random((2, 2)))
print(b)

print(np.vstack((a, b)))
print(np.hstack((a, b)))


[[9. 2.]
 [1. 9.]]
[[5. 3.]
 [6. 1.]]
[[9. 2.]
 [1. 9.]
 [5. 3.]
 [6. 1.]]
[[9. 2. 5. 3.]
 [1. 9. 6. 1.]]
